### ISSUE TITLE
Next/prev links broken

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#291] opened 2023-08-11 06:01 UTC
```[tasklist]
### Desiderata
- [ ] Diagnose the bug
- [ ] Fix it
- [ ] Confirm no other instances besides /whattomind
```

*(Updated with correct replicata. Lots of red herrings in the comments below!)*

## Replicata 

1. Go to http://blog.bmndr.co/whattomind
2. See the links to next and previous posts above the title
3. Click one

![image](https://github.com/beeminder/blog/assets/9928/455b5660-ce82-4b6b-968d-3a70a476a0d7)

## Expectata

To go to the next or previous post.

## Resultata

It tries to append the slug to the current URL.

_**Verbata**: broken links, mendoza,_

**Comment by dreeves** [comment] 2023-08-11 06:29
Oops, I just noticed you said this in Slack:

> I’m not seeing the next/previous post issue. What post is that screenshot from?

If you didn't fix this then there may be a heisenbug here. I'm failing to replicate it now but I don't think I was crazy last night. Maybe there's some circumstance that makes those links do the wrong thing?

**Comment by narthur** [comment] 2023-08-13 16:35
@dreeves What's our next action here? I've reviewed the code and wasn't able to come up with any theories as to why you may have seen this. And I'm still not able to reproduce manually.

**Comment by dreeves** [comment] 2023-08-14 01:48
I think we'll have to give up and close it as [CNR](https://xkcd.com/583/) and maybe keep an eye out in case we end up spotting it in the wild again?

**Comment by dreeves** [comment] 2023-08-15 21:59
I replicated it! I think it's like this:

## Replicata

1. Load a blog post, call it /foo
2. Trigger a deploy
3. Wait for the deploy to finish
4. Do shift-reload on the blog post
5. Click the link to the next post, which we'll call /bar

## Expectata

To go to blog.beeminder.com/bar

## Resultata

It tries to load blog.beeminder.com/foo/bar and 404s.

**Comment by dreeves** [comment] 2023-08-15 22:04
If that's what it takes to replicate the bug, users won't see it too often but they still could. Like if i'm fussing with a post and redeploying again and again then at some point the next/prev links will break for someone.

**Comment by dreeves** [comment] 2023-08-15 22:50
Wait, now I'm not sure if the above was a total red herring. It's staying broken for this blog post in particular:

https://blog.beeminder.com/whattomind/

**Comment by dreeves** [comment] 2023-08-16 23:35
Oops, and now it did fix itself?? Or was that you, @narthur?

**Comment by narthur** [comment] 2023-08-18 13:37
@dreeves Still looks broken to me.

**Comment by narthur** [comment] 2023-08-18 17:50
@dreeves I've pushed a fix for this issue. I'm still confused as to why it was intermittent. But I think it should be fixed now.

**Closed** 2023-08-19 19:13 UTC
Labels: zap, DEV, BUG, UVI, ZOM
